name: Dispatch Workflow

on:
  repository_dispatch:
    types:
      - load-test-trigger

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perform operation
        run: echo "Triggered by load-test-trigger event"

      - name: Install k6
        run: |
          if [ ! -f ./k6 ]; then
            curl -s https://dl.k6.io/releases/v0.45.0/k6-v0.45.0-linux-amd64.tar.gz | tar xz
            mv k6-v0.45.0-linux-amd64/k6 ./k6
          fi

      - name: Run k6 load test
        run: ./k6 run main.js
      
      - name: Upload summary.json
        uses: actions/upload-artifact@v4
        with:
          name: load-test-summary
          path: summary.json